# Generated by Django 2.0.3 on 2018-04-12 13:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180412_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileuploads',
            name='content',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
